name: Test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ 'oldstable', 'stable' ]
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: pass
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: pass
          MYSQL_DATABASE: droppable
        ports:
        - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping -ppass"
          --health-interval 10s
          --health-start-period 10s
          --health-timeout 5s
          --health-retries 10

    steps:
      - name: psql_setup
        run: >
          echo "*:*:*:*:pass" > $HOME/.pgpass
          && chmod 600 $HOME/.pgpass
          && psql --host localhost --username user -c 'CREATE DATABASE dialect_droppable;'
          && psql --host localhost --username user -c 'CREATE DATABASE driver_droppable;'

      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
          cache: true

      - name: Install Dependencies
        run: go mod download

      - name: Run tests
        env:
          PSQL_DIALECT_TEST_DSN: postgresql://user:pass@localhost:5432/dialect_droppable?sslmode=disable
          PSQL_DRIVER_TEST_DSN: postgresql://user:pass@localhost:5432/driver_droppable?sslmode=disable
          MYSQL_TEST_DSN: root:pass@(localhost:3306)/droppable?tls=skip-verify&multiStatements=true
        run: go test -race -covermode atomic -coverprofile=covprofile.out -coverpkg=github.com/stephenafamo/bob/... ./...

      - name: Send coverage
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: covprofile.out
