name: Test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ 'oldstable', 'stable' ]
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: droppable
          POSTGRES_USER: user
          POSTGRES_PASSWORD: pass
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      mysql:
        image: mysql/mysql-server:8.0
        env:
          MYSQL_ROOT_PASSWORD: pass
          MYSQL_DATABASE: droppable
        ports:
        - 33036:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
          cache: true

      - name: Install Dependencies
        run: go mod download

      - name: Run tests
        env:
          PSQL_TEST_DSN: postgresql://user:pass@localhost:5432/droppable?sslmode=disable
          MYSQL_TEST_DSN: root:pass@mysql:33036/droppable?tls=skip-verify&multiStatements=true
        run: go test -race -covermode atomic -coverprofile=covprofile.out -coverpkg=github.com/stephenafamo/bob/... ./...

      - name: Send coverage
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: covprofile.out
